### ISSUE TITLE
Tidal platform support

### ISSUE THREAD

**Issue by superfashi** [Runjuu/SongLink#1]
Tidal 和 Spotify 一样是国外的流媒体，只不过可以直接从国内访问，并且提供无损音质。曲库可以直接 [https://listen.tidal.com](https://listen.tidal.com) 访问，并且有各种 API 提供。希望添加支持。

**Comment by runjuu** [comment]
看起来不错，我试试

**Comment by superfashi** [comment]
谢谢，不过好像目前在专辑搜索上有点问题，希望改进。:smile:

**Comment by runjuu** [comment]
@hanbang-wang 目前搜索主要都是针对歌曲的，专辑的搜索还没列入开发计划 😂

TIDAL 的支持已经完成，安卓版本已经更新，App Store 那边还在审核(已经卡了2天了...)
