### ISSUE TITLE
希望添加 URL Scheme

### ISSUE THREAD

**Issue by soulsleuth** [Runjuu/SongLink#2]
Apple Music 没有相关的搜索 URL Scheme，希望通过本 App 一键搜索。

**Comment by runjuu** [comment]
能详细描述一下具体使用场景吗？

**Comment by soulsleuth** [comment]
例如在一些乐评网站看到专辑推荐，希望使用 URL Scheme 快速搜索。

**Comment by runjuu** [comment]
如果是用的 iOS，可以更新到最新版本使用 Share Extension 进行搜索

**Comment by runjuu** [comment]
例如下面这个 GIF，应该可以满足你的使用场景

![demo](https://i.imgur.com/7PHrRvK.gif)

**Comment by soulsleuth** [comment]
谢谢。
