### ISSUE TITLE
No spaces after comma

### ISSUE THREAD

**Issue by bbdav** [Runjuu/SongLink#4]
Overall helpful app, but when converting links from Spotify to apple music, track name which contains multiple artists names will be separated by comma without space, but apple music search won't accept queries with no spaces after commas and you won't get any results...

**Comment by runjuu** [comment]
Thanks for reporting. I will fix this issue ASAP 👻. By the way, which platform are you on?

**Comment by bbdav** [comment]
Sounds great, I'm on iOS 12.3.1 
Thank you!

**Comment by runjuu** [comment]
Hi, @bbdav I just released version 1.21 to fix this. 🍻

**Comment by bbdav** [comment]
Awesome, it just works!!
Thank you so much!
