### ISSUE TITLE
能否加入对酷狗音乐的支持

### ISSUE THREAD

**Issue by Eveg0** [Runjuu/SongLink#5]
你好，能否加入对酷狗音乐的搜索支持？

**Comment by runjuu** [comment]
@Eveg0 如果是 iOS 的话，我可以试试看，Android 最近不怎么有时间能维护了。

**Comment by Eveg0** [comment]
是 iOS 版。

________________________________
发件人: Huang <notifications@github.com>
发送时间: Wednesday, June 26, 2019 7:25:17 PM
收件人: Runjuu/SongLink
抄送: Eveg Chan; Mention
主题: Re: [Runjuu/SongLink] 能否加入对酷狗音乐的支持 (#5)


@Eveg0<https://github.com/Eveg0> 如果是 iOS 的话，我可以试试看，Android 最近不怎么有时间能维护了。

―

**Comment by runjuu** [comment]
@Eveg0 吼

**Comment by runjuu** [comment]
@Eveg0 新版本已经支持酷狗啦

**Comment by Eveg0** [comment]
好的。非常感谢！🙏

________________________________
发件人: Huang <notifications@github.com>
发送时间: Tuesday, July 2, 2019 10:46:50 AM
收件人: Runjuu/SongLink
抄送: Eveg Chan; Mention
主题: Re: [Runjuu/SongLink] 能否加入对酷狗音乐的支持 (#5)


@Eveg0<https://github.com/Eveg0> 新版本已经支持酷狗啦

**Comment by Eveg0** [comment]
有个问题，不能直接调取手机中的酷狗音乐app，只能网页播放。😅

________________________________
发件人: Huang <notifications@github.com>
发送时间: Tuesday, July 2, 2019 11:07:30 AM
收件人: Runjuu/SongLink
抄送: Eveg Chan; Mention
主题: Re: [Runjuu/SongLink] 能否加入对酷狗音乐的支持 (#5)


Closed #5<https://github.com/Runjuu/SongLink/issues/5>.

**Comment by runjuu** [comment]
嗯，目前是会有这个问题，要在网页上点击打开才行。我在下一个版本修复

**Comment by Eveg0** [comment]
好的。谢谢！

________________________________
发件人: Huang <notifications@github.com>
发送时间: Tuesday, July 2, 2019 11:21:31 AM
收件人: Runjuu/SongLink
抄送: Eveg Chan; Mention
主题: Re: [Runjuu/SongLink] 能否加入对酷狗音乐的支持 (#5)


嗯，目前是会有这个问题，要在网页上点击打开才行。我在下一个版本修复

―

**Comment by runjuu** [comment]
@Eveg0 新版本现在可以在设置界面启用「直接打开酷狗音乐」来解决这个问题了

**Comment by Eveg0** [comment]
已设置。非常感谢！😄

________________________________
发件人: Huang <notifications@github.com>
发送时间: Wednesday, July 10, 2019 11:29:19 PM
收件人: Runjuu/SongLink
抄送: Eveg Chan; Mention
主题: Re: [Runjuu/SongLink] 能否加入对酷狗音乐的支持 (#5)


@Eveg0<https://github.com/Eveg0> 新版本现在可以在设置界面启用「直接打开酷狗音乐」来解决这个问题了

**Comment by Eveg0** [comment]
你好，应用在下架了？？？🤔

________________________________
发件人: 陈 常青
发送时间: Wednesday, July 10, 2019 11:33:48 PM
收件人: Runjuu/SongLink <reply@reply.github.com>
主题: Re: [Runjuu/SongLink] 能否加入对酷狗音乐的支持 (#5)

已设置。非常感谢！😄

________________________________
发件人: Huang <notifications@github.com>
发送时间: Wednesday, July 10, 2019 11:29:19 PM
收件人: Runjuu/SongLink
抄送: Eveg Chan; Mention
主题: Re: [Runjuu/SongLink] 能否加入对酷狗音乐的支持 (#5)


@Eveg0<https://github.com/Eveg0> 新版本现在可以在设置界面启用「直接打开酷狗音乐」来解决这个问题了
